# Generated by Django 2.1.2 on 2019-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='preview',
            field=models.ImageField(default='', upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
